-- include another config
includefile("booconf2/config.lua")

-- define variables
variable = "This is a variable"

value_Listened = listen("script/example")
value_Polled = poll("2s", "script/examplePoll")

main = {
    bar = { "bar1", "bar2" }
}

bars = {
    bar1 = {
        width = "10%",
        offset_x = "20px",
        position = "TL",
        left_contents = "app_launcher"
    }

    bar2 = {
        width = "10%",
        offset_x = "20px",
        position = "TR",
        left_contents = "date"
    }
}

boo = {
    app_launcher = {
        -- config for app_launcher
    },
    date = {
        -- config for date
    }
}

custom = {
    custom_time = {
        time = poll("1s", "script/get_time"),
        type = "label",
        content = "<icon> " .. time
    }
}
